pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Build step running'
            }
        }

        stage('Test') {
            steps {
                echo 'Test step running'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy step running'
            }
        }
    }
}
